# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theater_name', models.CharField(blank=True, default='', max_length=100)),
                ('year_built', models.IntegerField()),
                ('location', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'ordering': ('theater_name',),
            },
        ),
    ]
